-- Product hub content upgrade. Idempotent UPDATEs.
PRAGMA foreign_keys = ON;

UPDATE products SET website_url = 'https://tokutei-taxi.vimai.jp', logo_url = '/images/products/tokutei_taxi.png', updated_at = strftime('%Y-%m-%dT%H:%M:%fZ','now') WHERE id = '00000000-0000-0000-0000-000000000001';
UPDATE product_translations SET name = 'ViMai Tokutei Taxi', tagline = '特定技能1号（タクシー）の学習アプリ', description = '外国人が日本の特定技能1号・タクシー分野の試験勉強と演習を行うためのアプリです。CBT形式の練習、模擬問題、誤答の見直し、学習のヒント、日本語とベトナム語、振り仮名、解説を備えています。', long_description = '試験の合格を保証するものではありません。出題形式に慣れることと、間違えた箇所を見直すことを目的とした学習ツールです。', target_audience = '日本でタクシー分野の特定技能1号を目指す外国人学習者。', features = '["CBT形式の練習", "模擬問題", "誤答の見直し", "学習のヒント", "日本語・ベトナム語", "振り仮名", "わかりやすい解説"]' WHERE product_id = '00000000-0000-0000-0000-000000000001' AND locale = 'ja';
UPDATE product_translations SET name = 'ViMai Tokutei Taxi', tagline = 'Ứng dụng luyện thi 特定技能1号 – Taxi', description = 'Ứng dụng dành cho người nước ngoài học và luyện thi 特定技能1号 ngành Taxi tại Nhật. Có luyện CBT, câu hỏi mô phỏng, ôn lại câu sai, mẹo làm bài, hỗ trợ tiếng Nhật và tiếng Việt, Furigana và phần giải thích.', long_description = 'Công cụ học tập để làm quen dạng đề và rà soát chỗ sai. Không cam kết đậu kỳ thi.', target_audience = 'Người nước ngoài tại Nhật đang chuẩn bị thi 特定技能1号 ngành Taxi.', features = '["Luyện dạng CBT", "Câu hỏi thi thử", "Ôn lại câu sai", "Mẹo làm bài", "Hỗ trợ tiếng Nhật và tiếng Việt", "Furigana", "Giải thích rõ ràng"]' WHERE product_id = '00000000-0000-0000-0000-000000000001' AND locale = 'vi';
UPDATE product_translations SET name = 'ViMai Tokutei Taxi', tagline = 'Study app for Specified Skilled Worker (i) Taxi', description = 'An app for foreigners studying and practicing for Japan’s Specified Skilled Worker (i) Taxi field. It includes CBT-style practice, mock questions, mistake review, study tips, Japanese and Vietnamese support, furigana, and explanations.', long_description = 'A study tool for exam format and review. It does not guarantee a passing result.', target_audience = 'Foreign residents in Japan preparing for Specified Skilled Worker (i) Taxi.', features = '["CBT-style practice", "Mock questions", "Mistake review", "Study tips", "Japanese and Vietnamese support", "Furigana", "Clear explanations"]' WHERE product_id = '00000000-0000-0000-0000-000000000001' AND locale = 'en';

UPDATE products SET website_url = 'https://tokutei-truck.vimai.jp', logo_url = '/images/products/tokutei_vantai.png', updated_at = strftime('%Y-%m-%dT%H:%M:%fZ','now') WHERE id = '00000000-0000-0000-0000-000000000002';
UPDATE product_translations SET name = 'ViMai Transport', tagline = '特定技能（自動車運送・トラック）の学習アプリ', description = '特定技能の運送・トラック分野に取り組む外国人向けの学習アプリです。対象者、学習の目的、模擬試験、日本語サポート、振り仮名、わかりやすい解説、日本での就労の方向性を整理して学べます。', long_description = '試験や就労の結果を保証するものではありません。学習範囲と出題形式を把握するためのツールです。', target_audience = '日本の特定技能・自動車運送業（トラック等）を目指す外国人学習者。', features = '["運送分野の学習目的が明確", "模擬試験", "日本語サポート", "振り仮名", "わかりやすい解説", "日本での就労に向けた方向づけ"]' WHERE product_id = '00000000-0000-0000-0000-000000000002' AND locale = 'ja';
UPDATE product_translations SET name = 'ViMai Transport', tagline = 'Ứng dụng luyện thi 特定技能 ngành vận tải / xe tải', description = 'Ứng dụng cho người học lĩnh vực 特定技能 vận tải / xe tải. Nêu rõ đối tượng, mục đích học, đề thi thử, hỗ trợ tiếng Nhật, Furigana, giải thích dễ hiểu và định hướng nghề nghiệp tại Nhật.', long_description = 'Công cụ nắm phạm vi học và dạng đề. Không cam kết kết quả thi hay việc làm.', target_audience = 'Người nước ngoài chuẩn bị thi và làm việc trong ngành vận tải / xe tải tại Nhật.', features = '["Mục tiêu học rõ ràng theo ngành vận tải", "Đề thi thử", "Hỗ trợ tiếng Nhật", "Furigana", "Giải thích dễ hiểu", "Định hướng nghề nghiệp tại Nhật"]' WHERE product_id = '00000000-0000-0000-0000-000000000002' AND locale = 'vi';
UPDATE product_translations SET name = 'ViMai Transport', tagline = 'Study app for Specified Skilled Worker transport / trucking', description = 'An app for foreigners studying the Specified Skilled Worker transport and trucking field. It highlights the audience, study purpose, practice exams, Japanese support, furigana, clear explanations, and career orientation in Japan.', long_description = 'A tool for understanding the study scope and exam format. It does not guarantee exam or employment outcomes.', target_audience = 'Foreign learners preparing for Specified Skilled Worker automobile transport / trucking in Japan.', features = '["Clear study purpose for transport work", "Practice exams", "Japanese-language support", "Furigana", "Clear explanations", "Career orientation in Japan"]' WHERE product_id = '00000000-0000-0000-0000-000000000002' AND locale = 'en';

UPDATE products SET website_url = 'https://seibi.vimai.jp', logo_url = '/images/products/sebishi_3kyu.png', updated_at = strftime('%Y-%m-%dT%H:%M:%fZ','now') WHERE id = '00000000-0000-0000-0000-000000000003';
UPDATE product_translations SET name = 'ViMai Seibi', tagline = '3級自動車整備士の学習アプリ', description = '3級自動車整備士（Seibi 3kyu）を学ぶ人のためのアプリです。対象者、学習範囲、外国人学習者への配慮、段階的な学習、わかりやすい構成を中心に設計しています。', long_description = '学科試験の学習を整理するためのツールです。合格を保証するものではありません。', target_audience = '3級自動車整備士の学科を学ぶ外国人および日本語学習者。', features = '["3級整備士の学習範囲に沿った構成", "外国人学習者への配慮", "段階的に進められる学習", "学科の基礎を整理"]' WHERE product_id = '00000000-0000-0000-0000-000000000003' AND locale = 'ja';
UPDATE product_translations SET name = 'ViMai Seibi', tagline = 'Ứng dụng học Seibi 3kyu (3級自動車整備士)', description = 'Ứng dụng học chứng chỉ Seibi 3kyu. Nêu rõ đối tượng, phạm vi học, hỗ trợ người nước ngoài, lộ trình có cấu trúc và điểm mạnh của sản phẩm.', long_description = 'Công cụ sắp xếp kiến thức thi lý thuyết. Không cam kết đậu kỳ thi.', target_audience = 'Người nước ngoài và người học tiếng Nhật đang ôn thi 3級自動車整備士.', features = '["Bám phạm vi Seibi 3kyu", "Hỗ trợ người học nước ngoài", "Học theo lộ trình có cấu trúc", "Hệ thống kiến thức lý thuyết"]' WHERE product_id = '00000000-0000-0000-0000-000000000003' AND locale = 'vi';
UPDATE product_translations SET name = 'ViMai Seibi', tagline = 'Study app for Seibi 3kyu (Class 3 automobile mechanic)', description = 'An app for studying Seibi 3kyu. It highlights the audience, curriculum scope, support for foreign learners, structured study, and the product’s strengths.', long_description = 'A tool for organizing written-exam study. It does not guarantee a passing result.', target_audience = 'Foreign learners and Japanese-language learners studying Class 3 automobile mechanic theory.', features = '["Curriculum aligned with Seibi 3kyu", "Support for foreign learners", "Structured learning path", "Written-exam knowledge organized clearly"]' WHERE product_id = '00000000-0000-0000-0000-000000000003' AND locale = 'en';

UPDATE products SET website_url = 'https://kids.vimai.jp', logo_url = '/images/products/vimai_kids.png', updated_at = strftime('%Y-%m-%dT%H:%M:%fZ','now') WHERE id = '00000000-0000-0000-0000-000000000004';
UPDATE product_translations SET name = 'ViMai Kids', tagline = '保護者向けに設計した子どもの学びアプリ', description = '子どもが文字、ひらがな、カタカナ、ベトナム語に触れ、練習モードで学べる教育アプリです。Apple Pencilに対応し、就学前の準備にも使えます。保護者が内容を把握しやすい設計です。', long_description = '家庭での学習を補助するアプリです。学校の成績や発達を保証するものではありません。', target_audience = '就学前〜小学校低学年のお子さまを持つ保護者。', features = '["文字の練習", "ひらがな・カタカナ", "ベトナム語", "練習モード", "Apple Pencil対応", "インタラクティブな学習", "就学前の準備"]' WHERE product_id = '00000000-0000-0000-0000-000000000004' AND locale = 'ja';
UPDATE product_translations SET name = 'ViMai Kids', tagline = 'Ứng dụng học cho trẻ, thiết kế cho phụ huynh', description = 'Ứng dụng giáo dục cho trẻ: chữ cái, Hiragana, Katakana, tiếng Việt, chế độ luyện tập, hỗ trợ Apple Pencil, học tương tác và chuẩn bị vào lớp. Giọng điệu dành cho phụ huynh theo dõi nội dung học của con.', long_description = 'Hỗ trợ học tại nhà. Không cam kết kết quả học đường hay phát triển.', target_audience = 'Phụ huynh có con ở độ tuổi mầm non đến đầu tiểu học.', features = '["Luyện chữ cái", "Hiragana và Katakana", "Tiếng Việt", "Chế độ luyện tập", "Hỗ trợ Apple Pencil", "Học tương tác", "Chuẩn bị vào lớp"]' WHERE product_id = '00000000-0000-0000-0000-000000000004' AND locale = 'vi';
UPDATE product_translations SET name = 'ViMai Kids', tagline = 'A children’s learning app designed for parents', description = 'An educational app for children covering letters, hiragana, katakana, Vietnamese, practice modes, Apple Pencil support, interactive learning, and preschool preparation. Written for parents who want to see what their child is practicing.', long_description = 'A home-learning aid. It does not promise school results or developmental outcomes.', target_audience = 'Parents of children in preschool through early elementary years.', features = '["Letter practice", "Hiragana and katakana", "Vietnamese", "Practice modes", "Apple Pencil support", "Interactive learning", "Preschool preparation"]' WHERE product_id = '00000000-0000-0000-0000-000000000004' AND locale = 'en';

UPDATE products SET website_url = 'https://maimai.vimai.jp', logo_url = '/images/products/maimai.png', updated_at = strftime('%Y-%m-%dT%H:%M:%fZ','now') WHERE id = '00000000-0000-0000-0000-000000000005';
UPDATE product_translations SET name = 'Maimai', tagline = '自分の生活指標を記録するアプリ', description = '体重、水分、睡眠、栄養、活動、周期、その他の個人指標を記録するヘルスケア／ライフスタイル記録アプリです。医療行為ではなく、日々の記録のためのツールです。', long_description = '診断・治療・予防の効果を示すものではありません。体調や健康の結果を保証しません。必要に応じて専門家に相談してください。', target_audience = '体重、睡眠、水分、栄養、活動、周期などを自分で記録したい人。', features = '["体重の記録", "水分摂取の記録", "睡眠の記録", "栄養の記録", "活動の記録", "周期の記録", "個人指標のカスタム"]' WHERE product_id = '00000000-0000-0000-0000-000000000005' AND locale = 'ja';
UPDATE product_translations SET name = 'Maimai', tagline = 'Ghi nhận chỉ số sinh hoạt cá nhân', description = 'Ứng dụng theo dõi lối sống: cân nặng, nước, ngủ, dinh dưỡng, hoạt động, chu kỳ và các chỉ số cá nhân. Không phải công cụ y tế; chỉ dùng để ghi nhận hằng ngày.', long_description = 'Không chẩn đoán, điều trị hay cam kết kết quả sức khỏe. Khi cần, hãy hỏi chuyên gia.', target_audience = 'Người muốn tự ghi nhận cân nặng, giấc ngủ, nước, dinh dưỡng, hoạt động và chu kỳ.', features = '["Ghi nhận cân nặng", "Ghi nhận lượng nước", "Ghi nhận giấc ngủ", "Ghi nhận dinh dưỡng", "Ghi nhận hoạt động", "Ghi nhận chu kỳ", "Chỉ số cá nhân tùy chỉnh"]' WHERE product_id = '00000000-0000-0000-0000-000000000005' AND locale = 'vi';
UPDATE product_translations SET name = 'Maimai', tagline = 'A personal health and lifestyle tracker', description = 'A lifestyle tracker for weight, water intake, sleep, nutrition, activity, cycle tracking, and other personal metrics. It is a daily log, not a medical device.', long_description = 'It does not diagnose, treat, or promise health outcomes. Consult a professional when you need medical advice.', target_audience = 'People who want to log weight, sleep, water, nutrition, activity, and cycle data themselves.', features = '["Weight logging", "Water-intake logging", "Sleep logging", "Nutrition logging", "Activity logging", "Cycle tracking", "Custom personal metrics"]' WHERE product_id = '00000000-0000-0000-0000-000000000005' AND locale = 'en';


